name: Reusable Security Scan

on:
  workflow_call:
    inputs:
      scan-type:
        description: 'Type of security scan (sast, dependency, all)'
        required: false
        default: 'all'
        type: string
      working-directory:
        description: 'Working directory for the workflow'
        required: false
        default: '.'
        type: string

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run CodeQL Analysis
        if: ${{ inputs.scan-type == 'sast' || inputs.scan-type == 'all' }}
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
      
      - name: Perform CodeQL Analysis
        if: ${{ inputs.scan-type == 'sast' || inputs.scan-type == 'all' }}
        uses: github/codeql-action/analyze@v3
      
      - name: Run Dependency Check
        if: ${{ inputs.scan-type == 'dependency' || inputs.scan-type == 'all' }}
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Stratovate-Solutions'
          path: ${{ inputs.working-directory }}
          format: 'ALL'
      
      - name: Upload Dependency Check results
        if: ${{ inputs.scan-type == 'dependency' || inputs.scan-type == 'all' }}
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/